### ISSUE TITLE
Support testing a token

### ISSUE THREAD

**Issue by swynter-ladbrokes** [tbruyelle/hipchat-go#15]
https://www.hipchat.com/docs/api/auth#auth_test

would probably be something like c.Room.Test(room/id) for example (all api endpoints support this apparently)

**Comment by tbruyelle** [comment]
If all API endpoint support this, I doens't like the idea to duplicate all methods with a Test variant.

Another solution would be to have a `NewTestClient` method, which wraps the `NewClient` but enables a test flag. Then in `NewRequest`, when this test flag is true, we add the `auth_test=true` parameter.

WDYT?

**Comment by tbruyelle** [comment]
@swynter-ladbrokes I finally find the time and the way to add this feature. Look at the readme to see how you can use it.
HTH
