### ISSUE TITLE
library throws away temporary/permanent error information

### ISSUE THREAD

**Issue by hnsl** [tbruyelle/hipchat-go#24]
If I use this library to send a message it currently throws away the HTTP status code. It's not possible to know from the error if the error is temporary or permanent. For example, on network errors and 5xx I want to try again. Possible solutions is always returning the http client even on errors or alternatively creating an error type that can be interrogated for temporariness.

**Comment by hnsl** [comment]
Also slightly related is that the error information is really spartan. I just get a "Server returns status 401" back on error and no other real details. If the API actually provides more error information you might want to include that in the actual error, especially if you go with a custom error type.

**Comment by tbruyelle** [comment]
Every methods return the `http.Response`, you should find everything you need inside.

**Comment by hnsl** [comment]
True, I goofed when I read the code.
