### ISSUE TITLE
using Card in Notification

### ISSUE THREAD

**Issue by crisarceramos** [tbruyelle/hipchat-go#28]
Hi Dev team this is not really an issue but a request. Are you able to provide a working example of notification with Card object. When I add card object in my notification, I get HTTP 400 error. Not sure why. My goal is to post a notification with link where when the user click the link it will open a dialog displaying some text. Thank you!

**Comment by tbruyelle** [comment]
Did you enable Hipchat Connect in your preferences ?

**Comment by crisarceramos** [comment]
sorry not sure or understand how to set that. I actually use hipchat-go and develop a web server using golang. so the app will create a hook on hipchat and will listen to http request. it's not running as add-on for hipchat. when i send notification to the room, it's working. but when I used Card struct, I get 400 error.

**Comment by tbruyelle** [comment]
I'm talking about your Hipchat user account, there's some preferences where you must enable HipChat Connect to use the new Card API (your Hipchat user must be admin of your Hipchat instance to actually see that option).

**Comment by crisarceramos** [comment]
Thanks tbruyelle. that makes it clear for me.
