### ISSUE TITLE
Using any HTTP client in hipchat.Client

### ISSUE THREAD

**Issue by shkw** [tbruyelle/hipchat-go#29]
Hi,

I'm considering using this library on a Google App Engine module, so I want to use `hipchat.Client` with an HTTP client returned by [urlfetch.Client](https://godoc.org/google.golang.org/appengine/urlfetch#Client) function. But, as of now, `hipchat.Client` always uses http.DefaultClient and there's no way to replace it.

I believe it would be really useful if an HTTP client can be specified to `hipchat.NewClient` like [go-github.NewClient](https://godoc.org/github.com/google/go-github/github#NewClient). I understand this could be a breaking change, however, following it is very easy and it is just to replace `hipchat.NewClient(token)` with `hipchat.NewClient(nil, token)`. Just adding a method like `SetHTTPClient(*http.Client)` to `hipchat.Client` might be enough if such breaking change is not acceptable

Does anyone have any thoughts on this?

If one of the above suggestions is acceptable, I can work on a PR to make changes accordingly.

**Comment by tbruyelle** [comment]
Well I think a setter will be ok. 

Changing the constructor would be better but I don't like breaking all the clients of this library.

I will accept your PR quickly, thanks in advance.

**Comment by shkw** [comment]
Thanks for your response.
I will add a setter method and then send a PR later.
