### ISSUE TITLE
bot can post notification to hipchat rooms but hipchat not able to send request to bot server.

### ISSUE THREAD

**Issue by crisarceramos** [tbruyelle/hipchat-go#32]
Hi Dev team,
This is not an issue, I just need you expert advise on how to configure my bot developed with this package. The bot I developed is deployed in a company owned dev env. The bot is running on port 443 and was able to send notification to HipChat rooms. Unfortunately, the bot is not receiving any request coming from HipChat.

When I test in my local machine using ngrok to expose my bot, it works fine w\o issue. But when I deploy to our dev env w\o ngrok, the issue occurs. 

What could be the requirement in order for HipChat to send request to my bot?
Do I need certificates? Should the HipChat server have network access to the bot server?
I lack knowledge in this area and appreciate any advise. 

Many thanks.

**Comment by tbruyelle** [comment]
Hi, your question is pure network, I'm not sure I can help.
Do you use a room webhook or Hipchat Integration for sending request to your bot ?

**Comment by crisarceramos** [comment]
I use room webhook. i don't install the bot as addon. it just communicates to HipChat API2.
when running, it servers port 443 waiting for any request from HipChat via webhook initialized.
While the bot can send notification to any valid chatrooms, HipChat is not able to send request to my bot. but if i used ngrok for testing, Hipchat was able to send request to my bot.

**Comment by tbruyelle** [comment]
Well the url without ngrok you provide when subscribing the webhook seems
not reachable from hipchat...

**Comment by tbruyelle** [comment]
If you use https it may be a certificate issue.

Le sam. 20 févr. 2016 10:47, Thomas Bruyelle <thomas.bruyelle@gmail.com> a
écrit :

> Well the url without ngrok you provide when subscribing the webhook seems
> not reachable from hipchat...
>
