### ISSUE TITLE
New feature: API Rate Limiting, auto-retry

### ISSUE THREAD

**Issue by afinkenstadt** [tbruyelle/hipchat-go#46]
cf:  https://developer.atlassian.com/hipchat/guide/hipchat-rest-api/api-rate-limits

implement automatic retry when API rate limited

pull request to come, unless it's already in queue

**Comment by afinkenstadt** [comment]
@tbruyelle 

I plan to add another `hipchat` package variable which controls whether to do retries on `HTTPStatusCode 429`, in the same style as the `AuthTest`.  I'll also add information to the `Room` and `User` structures which records the latest returned headers to allow inspection by the host program using hipchat-go.

```
X-Ratelimit-Limit: 100
X-Ratelimit-Remaining: 69
X-Ratelimit-Reset: 1476919340
```

**Comment by tbruyelle** [comment]
Nope
