### ISSUE TITLE
I can't make a message with new line 

### ISSUE THREAD

**Issue by medyagh** [tbruyelle/hipchat-go#57]
I tried the following and none of them work

```
notifyHipchat("/code This \n is \n a \n message")
notifyHipchat("This \n is \n a \n message")
notifyHipchat("This \\n is \\n a \\n message")
notifyHipchat(`This
 is
 a
 message`)
notifyHipchat(`This \nis \na \nmessage`)
```

**Comment by tbruyelle** [comment]
I think you have to change the type of the message (html or text)

**Comment by crisarceramos** [comment]
@medyagh if you are using /code then set MessageFormat as text.
if not using /code, set MessageFormat as html and replace all occurrence of \n with <br> on your actual message.

**Comment by medyagh** [comment]
Thanks I ended up using html type
